name: flutter_battery_meter # Plugin name (lowercase, no spaces)
description: A Flutter plugin to get battery level on Android & iOS
version: 1.0.0 # Start with 1.0.0
homepage: https://github.com/aniket312001/battery_level_plugin
repository: https://github.com/aniket312001/battery_level_plugin

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: dev.aniketchavan505.flutter_battery_meter
        pluginClass: BatteryLevelPlugin
      ios:
        pluginClass: BatteryLevelPlugin
